### PR TITLE
Fix detected I/O inside the event loop issue

### PR DESCRIPTION
**Pull request by ovid-io**
This PR fixes the below issue with HA 0.109+

```
2020-05-04 11:24:21 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sems2mqtt doing I/O at custom_components/sems2mqtt/__init__.py, line 116: r = requests.post(base_url + url, headers=headers, data=payload, timeout=20)

2020-05-04 11:24:21 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sems2mqtt doing I/O at custom_components/sems2mqtt/__init__.py, line 124: r = requests.post(global_url + 'v1/Common/CrossLogin', headers=headers, data=loginPayload, timeout=20)
```

### CODE REVIEW

**Comment by UnrealKazu** [comment]
Can confirm that this indeed fixes the issue. Would be great if it can be merged.

**Comment by GLD-NL** [comment]
I can also confirm that this fixed the issue. Great work!

Thanks a lot.

**Comment by bouwew** [comment]
@ovid-io @GLD-NL Thanks guys! 
I had not noticed this PR for some reason. I will follow the changes that are proposed, plus a few more, they will be released in version 0.2.0.

**Comment by bouwew** [comment]
@ovid-io @GLD-NL I see that another user of a fork is using SEMS API v2.
I wonder if that is an update that I should include.

Could you test the v2 API?
Also, would you mind testing the latest sems2mqtt beta version v0.2.0b6?

**Comment by ovid-io** [comment]
Hi @bouwew, I'm unsure about v2 api, if you can point me to the right direction happy to test

**Comment by bouwew** [comment]
@ovid-io I got the idea from here https://github.com/videgro/sems2mqtt/commit/a98458963b222fca3a114fe45ac5bb8a47c502a2
I think the v2 API shows more sensors, look at the other changes on the newer commits: https://github.com/videgro/sems2mqtt/commits/master

**Pull request closed without merging**
